# Use the official Node.js image as a base
FROM node:18

# Set the working directory inside the container
WORKDIR /app


COPY . .
# Install dependencies
RUN npm install

# Copy the rest of the backend files



# Start the backend server
CMD ["node","server.js"]